forum/urls.py
from django.urls import path
from . import views

app_name="forum"
urlpatterns = [
    path("forum/", views.forum, name="forum"),
    path("post/", views.post, name="post"),
    path("announce/", views.announce, name="announce"),
    path("forum/suggestion/<int:suggestion_id>", views.suggestion, name="suggestion"),
    path("forum/announcement/<int:announcement_id>", views.announcement, name="announcement")
]

litter/urls.py
from django.urls import path

from . import views

app_name="litter"
urlpatterns = [
    path("latest/", views.latest, name="latest"),
    path("instance/<int:instance_id>/", views.instance, name="instance"),
    path("report/", views.report, name='report'),
    path("heatmap/", views.heatmap, name='heatmap'),
    path("your-instances/", views.your_instances, name="your instances"),
]

poi/urls.py
from django.urls import path

from . import views

app_name="poi"
urlpatterns = [
    path("map/", views.map, name="map"),
    path("info/<int:poi_id>/", views.information, name="info"),
    path("submit/", views.submit, name='submit'),
]

sustainable_challenges/account/urls.py
# urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import reverse_lazy

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('authuser:login')

app_name = "account"
# paths to app
urlpatterns = [
    path("user_account", views.user_account, name='user_account'),
    path("admin_account", views.admin_account, name='admin_account'),
    path("reset_email/", views.reset_email, name='reset_email'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/<uidb64>/<token>/complete/', views.password_reset_complete, name='password_reset_complete'),
]

sustainable_challenges/game/urls.py
from django.urls import path


from . import views

app_name="game"
# The url paths for the game app
urlpatterns = [
    path("", views.game, name="game"),
    path("shop", views.shop, name="shop"),
    path("raffle", views.raffle, name="raffle")
]

sustainable_challenges/home/urls.py
from django.urls import path

from authuser.views import login_view
from . import views

app_name="home"
urlpatterns = [
    path("", views.index, name="index"),
    path("goals/", views.goals, name="goals"),
    path("privacy/", views.privacy, name="privacy")
]

sustainable_challenges/sustainable_challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sustainable_challenges'

urlpatterns = [
    path('litter/', include('litter.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('authuser.urls')),
    path('game/', include('game.urls')),
    path('account/', include('account.urls')),
    path('study_area/', include('study_area.urls')),
    path('forum/', include('forum.urls')),
    path('poi/', include('poi.urls')),
    path('leaderboard/', include('leaderboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustainable_challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sustainable_challenges'

urlpatterns = [
    path('litter/', include('litter.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('authuser.urls')),
    path('game/', include('game.urls')),
    path('account/', include('account.urls')),
    path('study_area/', include('study_area.urls')),
    path('forum/', include('forum.urls')),
    path('poi/', include('poi.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustainable_challenges/home/views.py
from django.shortcuts import render


def index(request):
    return render(request, '../home/index.html', {"is_staff": request.user.is_staff})

def goals(request):
    return render(request, '../home/goals.html', {"is_staff": request.user.is_staff})

def privacy(request):
    return render(request, '../home/privacy.html', {"is_staff": request.user.is_staff})

sustainable_challenges/home/templates/home/base.html
<html lang - "en">

<head>
    {% block head %}
    <title>Sustainable Challenges</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="icon" href="{% static 'favicon.png' %}">
    {% endblock %}
</head>

<body style="background-color: #007d69; padding-top: 100px;">
    <div class="container-fluid">
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color: #007d69">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" href="/">Sustainable Challenges</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav  ms-auto mb-2 mb-lg-0">
                        <!--if user is logged in:-->
                        {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">Litter</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'litter:report' %}">Submit Report</a></li>
                                <li><a class="dropdown-item" href="{% url 'litter:your instances' %}">Your Reports</a>
                                </li>
                                {% if is_staff %}
                                <li><a class="dropdown-item" href="{% url 'litter:latest' %}">Latest</a></li>
                                <li><a class="dropdown-item" href="{% url 'litter:heatmap' %}">Litter Heatmap</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="studySpaceDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">Places of Interests</a>
                            <ul class="dropdown-menu" aria-labelledby="studySpaceDropdown">
                                <li><a class="dropdown-item" href="/poi/map">Map</a></li>
                                {% if is_staff %}
                                <li><a class="dropdown-item" href="/poi/submit">Create</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="studySpaceDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">Events</a>
                            <ul class="dropdown-menu" aria-labelledby="studySpaceDropdown">
                                <li><a class="dropdown-item" href="{% url 'home' %}">Home</a></li>
                                <li><a class="dropdown-item" href="{% url 'event' %}">Events</a></li>
                                {% if is_staff %}
                                <li><a class="dropdown-item" href="{% url 'create_event' %}">Create</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">Forum</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'forum:forum' %}">Posts</a></li>
                                <li><a class="dropdown-item" href="{% url 'forum:post' %}">Make a post</a></li>
                                {% if is_staff %}
                                <li><a class="dropdown-item" href="{% url 'forum:announce' %}">Make announcement</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'game:game' %}">Game</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="shopRaffleDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="shopRaffleDropdown">
                                <li><a class="dropdown-item" href="{% url 'game:shop' %}">Point Shop</a></li>
                                <li><a class="dropdown-item" href="{% url 'game:raffle' %}">Raffle</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">About us</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'home:goals' %}">Our goals</a></li>
                                <li><a class="dropdown-item" href="{% url 'home:privacy' %}">Privacy policy</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'leaderboard:leaderboard' %}">Leaderboard</a>
                        </li>
                        {% if is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:admin_account' %}">Account</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:user_account' %}">Account</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="/login/logout">Logout</a>
                        </li>
                        <!--if user is not logged in-->
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/login">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/login/register">Sign up</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

sustainable_challenges/home/templates/home/goals.html
{% extends 'home/base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="title">
    <h1>Our goals</h1>
</div>
<div class="body">
    <h5>The University of Exeter aims to have a carbon net zero impact by 2030, and we want to help!</h5>
    <br>
    <h5>Our goals:</h5>
    <ul>
        <li>Lead meaningful action against the climate emergency and ecological crisis.</li>
        <li>Make key breakthroughs to transform human health and wellbeing.</li>
        <li>Lead progress towards creating a fair, socially just and inclusive society.</li>
    </ul>
</div>
{% endblock %}

sustainable_challenges/home/templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'index.css' %}" />
<div class="container welcome">
    <h1>Welcome to Sustainable Challenges</h1>
    <br />
    <!-- {% if request.user.is_authenticated %}
        {% if is_staff %}
        <div class="badge text-wrap" style="background-color: #007d69;">
            <h2>You are logged in as an admin.</h2>
        </div>
        {% else %}
        <div class="badge text-wrap" style="background-color: #007d69;">
            <h2>You are logged in as a user.</h2>
            <h3>Click <a href="/game">here</a> to play the game!</h3>
        </div>
        {% endif %}
    {% else %}
    <div class="badge text-wrap" style="background-color: #007d69;">
        <p>You appear to not be signed in. Click here to <a href="/login">Log in</a>.</p>
        <p>To create an account, click <a href="/login/register">here</a>.</p>
    </div>
    {% endif %} -->
    <div class="row">
        <div class="col-sm-12 green-border p-0 mb-5">
            <ul class="list-group">
                <li class="list-group-item text-center">
                    <h2>The Game</h2>
                    <br />
                    Completing any task will reward you with points that can be used to redeem vouchers or enter sweepstakes. There are 
                    also challenges that reward a higher number of points, and progress you to the next level.
                </li>
                <li class="list-group-item text-center">
                    <h2>Litter</h2>
                    <br />
                    You can report instances of litter you see around campus by taking a photo of them and uploading them.
                    Your report will then be submitted for approval. A game keeper will review it and either accept it or reject it.
                    In the event it is acceptted, you will recieve points and progress your challenges.
                    <br />
                    {% if is_staff %}
                    As a game keeper, you can also report instances of litter however, you cannot approve your own report.
                    There is also a heatmap to display litter hotspots around campus.
                    {% endif %}
                </li>
                <li class="list-group-item text-center">
                    <h2>Events</h2>
                    <br/>
                    You can view upcoming and currently occurring events on campus as well as information related to them. 
                    Once you are at the location of the event, you can confirm that you have attended the event and receive points.
                    The confirmation button will not appear until the event is occuring.
                    <br />
                    {% if is_staff %}
                    As a game keeper, you can create events, and the location will be set to your current location/router access point.
                    You can view the event details regardless of where you are accessing it from, and you can also renew the IP for the location
                    in the scenario that the router IP is renewed.
                    {% endif %}
                </li>
                <li class="list-group-item text-center">
                    <h2>Places of Interest</h2>
                    <br />
                    As you walk around campus, you can view places of interest on the map and visit them. You must be close to the place
                    to be able to say you've visited it, you can only recieve points for visiting a place once. The places of interest
                    will have the theme of promoting sustainability.
                    <br/>
                    {% if is_staff %}
                    As a game keeper, you can submit new places of interest and also visit them.
                    {% endif %}
                </li>
                <li class="list-group-item text-center">
                    <h2>Forum</h2>
                    <br />
                    You can create posts and comment on them. Posts can be endoresed by others and allow for discussions between users.
                    These posts can also be used as a way to make recommendations on how the university can achieve its sustainability
                    goals.
                    <br/>
                    {% if is_staff %}
                    As a game keeper, you can moderate posts and remove them if necessary. You can create announcements which are placed 
                    at the top of the forum and are meant to be used as way to inform users of initiatives or changes.
                    {% endif %}
                </li>
                <li class="list-group-item text-center">
                    <h2>Raffle</h2>
                    <br />
                    There is a daily and weekly raffle you can enter for a chance to win more points. The daily raffle can be entered for free
                    and the weekly raffle has an entry cost of 100 points. The raffle is drawn at 3pm daily, and at the same time on Friday for the weekly one.
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

sustainable_challenges/home/templates/home/privacy.html
{% extends 'home/base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="title">
    <h1>Privacy Policy</h1>
</div>
<div class="body">
    <h4>Type of private information collected</h4>
    <p>To provide the best experience to you as a user, we collect the following types of information when you visit our website and use our app.</p>
    <h5>Personal information</h5>
    <p>We collect the following personal information from our users:</p>
    <ul>
        <li>First name</li>
        <li>Last name</li>
        <li>Email address</li>
    </ul>
    <p>You can always choose to provide less information. However, omitting some of this personal information may limit your ability to access all of the benefits of our website and app.</p>
    <h5>Location-based information</h5>
    <p>Certain features of our website and app require us to collect your information about your location.</p>
    <p>You can always choose to deny sharing your location. However, doing so may limit functionality of some features of our website and app.</p>
    <h5>Automatically collected information</h5>
    <p>We automatically collect data on how our users visit our website, such as your IP address, browser, browser language, operating system, device identifiers, and cookies.</p>
    <p>Our website currently uses cookies to enhance its functionality. You may disable cookies in your web browser, but this may limit your ability to access our website.</p>
    <br>
    <h4>How the information collected is used</h4>
    <p>How your information is handled will fully comply with all GDPR guidelines.</p>
    <p>We only use your personal information to help you utilise everything we have to offer. This includes:</p>
    <ul>
        <li>Creating and maintaining an account with us</li>
        <li>Accessing all features of our website and app</li>
        <li>Making all of our services available to you in a convenient manner</li>
        <li>Contacting you regarding updates to our policies</li>
    </ul>
    <br>
    <h4>Length of time personal information is stored</h4>
    <p>We may store your personal information for an extended period of time, depending on how we need to use the information. We will comply with GDPR guidelines to ensure your information is only stored for as long as necessary.</p>
    <br>
    <h4>Who the information is shared with</h4>
    <p>How your information is shared will fully comply with all GDPR guidelines.</p>
    <p>For some of the features in our website and app, we use a third-party API for map technology. We may share your location information with this service in order to provide the best experience for you. However, we will ensure your data is shared securely and will not be seen by anyone else.</p>
    <p>We will not share your personal information with any other third-party companies or services.</p>
    <br>
    <h4>Information security</h4>
    <p>We do our best to keep your private information secure and safe, complying with all GDPR guidelines.</p>
    <p>Most of your personal information is encrypted and is therefore protected from being accessed by outsider users. However, data leaks and malicious attack do happen. Please understand that while we do our best to protect your data, we cannot completely guarantee security of information, so providing your personal information is at your own risk.</p>
    <br>
    <h4>Ability to decline to provide personal information</h4>
    <p>Following GDPR guidelines and regulation, you can, of course, decline to disclose your personal information to us. However, the failure to provide us with relevant information may limit your ability to fully benefit form our website and app, and all of its offerings. Remember, we only ask for personal information that can help us fully  provide services to our customers.</p>
    <br>
    <h4>You can download a copy of our privacy policy <a href="{% static 'Privacy Policy.pdf' %}" download="Privacy Policy.pdf">here</a></h4>
</div>
{% endblock %} 