poi/urls.py
from django.urls import path

from . import views

app_name="poi"
urlpatterns = [
    path("map/", views.map, name="map"),
    path("info/<int:poi_id>/", views.information, name="info"),
    path("submit/", views.submit, name='submit'),
]

sustainable_challenges/sustainable_challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sustainable_challenges'

urlpatterns = [
    path('litter/', include('litter.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('authuser.urls')),
    path('game/', include('game.urls')),
    path('account/', include('account.urls')),
    path('study_area/', include('study_area.urls')),
    path('forum/', include('forum.urls')),
    path('poi/', include('poi.urls')),
    path('leaderboard/', include('leaderboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustainable_challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sustainable_challenges'

urlpatterns = [
    path('litter/', include('litter.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('authuser.urls')),
    path('game/', include('game.urls')),
    path('account/', include('account.urls')),
    path('study_area/', include('study_area.urls')),
    path('forum/', include('forum.urls')),
    path('poi/', include('poi.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poi/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL

class PlaceOfInterest(models.Model):
    '''
    Database model for storing an instance of litter

    Fields
    ------
    desc: string
          Description and information about the place of interest
    lat: float
         The latitude of the reports location
    lon: float
         The longitude of the reports location
    '''
    title = models.CharField("Title", max_length=100)
    desc = models.TextField("Description")
    lat = models.DecimalField("Latitude", decimal_places=16, max_digits=19)
    lon = models.DecimalField("Longitude", decimal_places=16, max_digits=19)

    def __str__(self):
        return f"{self.lat}, {self.lon} | {self.desc}"
    

class VisitedPlaceOfInterest(models.Model):
    '''
     Database table to keep track of what users have visited where
     so that a user cannot vist the same place twice and get points for it again.
    
     Fields
     ------
     user: Django user
          The user that has visted the palce
     place: PlaceOfInterest
            The place that has been visited
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")
    place = models.ForeignKey(PlaceOfInterest, on_delete=models.CASCADE, verbose_name="Place Of Interest")

    def __str__(self):
        return f"{self.user} @ {self.place}"

poi/forms.py
from django import forms
from .models import PlaceOfInterest

class PlaceOfInterestForm(forms.ModelForm):
    '''
    The Form for submitting a place of interest
    '''
    class Meta:
        model = PlaceOfInterest
        fields = ('title', 'desc','lat', 'lon')

        widgets = {
            'lat': forms.NumberInput(attrs={'id':'lat_id'}),
            'lon': forms.NumberInput(attrs={'id':'lon_id'}),
        }

class LocationForm(forms.Form):
    '''
    The form for getting the users location when they try to visit a place
    '''
    lat = forms.DecimalField(widget=forms.NumberInput(attrs={'id':'lat_id', 'hidden': 'hidden'}), label="")
    lon = forms.DecimalField(widget=forms.NumberInput(attrs={'id':'lon_id', 'hidden': 'hidden'}), label="")

sustainable_challenges/poi/views.py
from typing import Any
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse, HttpResponseForbidden
from .models import PlaceOfInterest, VisitedPlaceOfInterest
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from .forms import PlaceOfInterestForm, LocationForm
from json import dumps
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from typing import Union

# Create your views here.

@login_required
def submit(request: HttpRequest) -> Union[HttpResponse, HttpResponseRedirect, HttpResponseForbidden]:
    '''
    Endpoint for game keepers to create a new place of interest

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django

    Returns
    -------
    HttpResponse or HttpResponseRedirect
        Containing the submit.html webpage.
        If HttpResponseRedirect it means that a POST request was received and a new place of interest was created
    '''
    if not request.user.is_staff:
        return HttpResponseForbidden()

    submitted = False
    id = -1
    if request.method == "POST":
        # Populate the form with the POST data
        form = PlaceOfInterestForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            poi = PlaceOfInterest.objects.get(pk=obj.id)
            return HttpResponseRedirect(f'/poi/submit?submitted=True&id={poi.id}')
    else:  # Is a GET request
        # Create a blank form
        form = PlaceOfInterestForm
        # Check if the GET request is a result of the redirect after a post
        if 'submitted' in request.GET and 'id' in request.GET:
            submitted = True
            id = request.GET['id']

    return render(request, 'poi/submit.html', {'form': form, 
                                                'submitted': submitted, 
                                                'id': id,
                                                'is_staff': request.user.is_staff})

@login_required
def information(request: HttpRequest, poi_id: int) -> Union[HttpResponse, HttpResponseRedirect]:
    '''
    Endpoint for users to view additional information about a place of interest

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django
    poi_id : int
             The id of the place of interest to display information for

    Returns
    -------
    HttpResponse or HttpResponseRedirect
        Containing the info.html webpage.
        If HttpResponseRedirect it means that a POST request was received and a user visited a place of interest
    '''
    # Get the place of interest to display info for
    poi = get_object_or_404(PlaceOfInterest, pk=poi_id)
    submitted = False
    close = False
    visited = False

    # See if the user has already visited this place of interest
    try:
        VisitedPlaceOfInterest.objects.get(user=request.user, place=poi)
        visited = True
    except ObjectDoesNotExist:
        visited = False

    if request.method == "POST" and visited == False:  # If they haven't visited it and wish to
        form = LocationForm(request.POST)
        if form.is_valid():
            lat = float(form.cleaned_data['lat'])
            lon = float(form.cleaned_data['lon'])
            lat_delta = abs(lat - float(poi.lat)) 
            lon_delta = abs(lon - float(poi.lon)) 
            if lat_delta <= 0.001 and lon_delta <= 0.001:  # 111 meter difference between user location and poi location
                close = True
                VisitedPlaceOfInterest.objects.create(user=request.user, place=poi)
                request.user.complete_task("interest")
            return HttpResponseRedirect(f'/poi/info/{poi_id}?submitted=True&close={close}')
    else:
        form = LocationForm
        if 'submitted' in request.GET and 'close' in request.GET:
            submitted = True
            close = request.GET['close']

    # json so the js can add the point marker to the map
    json_dict = {'lat': poi.lat, 'lon': poi.lon, 'close': close}

    return render(request, 'poi/info.html', {'visited': visited,
                                             'close': close,
                                             'submitted': submitted,
                                             'poi': poi,
                                             'lat_lon': json_dict,
                                             'form': form,
                                             'is_staff': request.user.is_staff})

def map(request: HttpRequest) -> HttpResponse:
    '''
    Endpoint for users to view places of interest on a map and view their location

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django

    Returns
    -------
    HttpResponse
        Containing the map.html webpage.
    '''
    pois = PlaceOfInterest.objects.all()
    poi_list = []
    for poi in pois:
        poi_list.append({'title': poi.title, 'desc': poi.desc, 'lat': poi.lat, 'lon': poi.lon, 'id': poi.id})
    json_dict = {'places': poi_list}
    return render(request, 'poi/map.html', {'json_dict': json_dict,
                                            'is_staff': request.user.is_staff})

poi/templates/poi/info.html
{%  extends "base.html" %}
{% block content %}
{% load static %}
<script src="{% static 'info.js' %}" defer></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
{{ lat_lon|json_script:"position" }}
<div class="row">
    <div class="col-sm-12 col-lg-6 justify-content-center align-items-center">
        <div class="d-flex flex-column h-100">
            <ul class="list-group border border-secondary">
                <li class="list-group-item list-group-item-dark text-center text-black"><strong>TITLE</strong></li>
                <li class="list-group-item text-center">{{ poi.title }}</li>
                <li class="list-group-item list-group-item-dark text-center text-black"><strong>DESCRIPTION</strong></li>
                <li class="list-group-item text-center">{{ poi.desc }}</li>
            </ul>
    
            <br/>
            {% if visited == False %}
                {% if submitted == True %}
                    <div class="d-felx align-items-end h-100">
                        <div id="close" class="d-felx justify-content-center w-100 text-center bg-white rounded py-3 mb-3">
                        </div>
                    </div>
                {% else %}
                    <div class="d-flex align-items-end h-100">
                        <form id="loc_form" class="d-flex justify-content-center w-100 bg-white rounded" action="" method="POST">
                            {% csrf_token %}
                            <div class="m-2">{{ form.as_p }}</div>
                            <div class="m-2"><button onclick="get_loc()" class="btn btn-danger">Vist</button></div>
                        </form>
                    </div>
                {% endif %}
            {% else %}
                    <div class="d-felx align-items-end h-100">
                        <div class="d-felx justify-content-center w-100 text-center bg-white rounded py-3 mb-3">
                            You have visited this place.
                        </div>
                    </div>
            {% endif %}
        </div>
    </div>
    <div class="col-sm-12 col-lg-6 d-flex justify-content-center align-items-center">
        <div class="container-fluid p-4 border border-secondary bg-white d-flex justify-content-center rounded">
            <div style="width: 600; height: 400;">
                <div id="map" class="w-100 h-100"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

poi/templates/poi/map.html
{%  extends "base.html" %}
{% block content %}
{% load static %}
<script> 
    var img_src="{% static 'loc_icon.png' %}";
</script>
<script src="{% static 'map.js' %}" defer></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<style>
    #map {position: absolute; top: 80; bottom: 25; left: 25; right: 25;}
</style>
{{ json_dict|json_script:"places" }}
<div class="row">
    <div class="col-sm-12">
        <div id="map" class=""></div>
    </div>
</div>
{% endblock %}

poi/templates/poi/submit.html
{%  extends "base.html" %}
{% block content %}
{% load static %}
<script src="{% static 'submit.js' %}" defer></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<div class="row d-flex justify-content-center">
    <!-- <div class="col-sm-12 col-md-8"> -->
        <!-- <div class="container-fluid"> -->
            <!-- <div class="row d-flex justify-content-center"> -->
                {% if submitted %}
                    <div class="col-sm-8 col-md-6 d-flex justify-content-center bg-white rounded mb-0">
                        <div class="row justify-content-center align-items-center">
                            <div class="col-sm-12 justify-content-center align-items-center text-center mt-5">
                                Place of interest successfully submitted.
                            </div>
                            <div class="col-sm-12 d-flex justify-content-center align-items-center mb-5">
                                <a role="button" class="btn btn-success" href="{% url 'poi:info' id %}">View</a>
                                <!-- <button class="btn btn-success" href="{% url 'poi:info' id %}">View</button> -->
                            </div>
                        </div>
                        <!-- <div class="row justify-content-center align-items-center">
                        </div> -->
                    </div>
                {% else %}
                <form class="col-sm-8 col-md-6 d-flex justify-content-center align-items-center bg-white rounded mb-0" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="">
                        <!-- <div class="row ">
                            <div class="col-sm-8 d-flex align-items-center justify-content-center"> -->
                                <div class="row d-flex justify-content-center">
                                    <div class="col-sm-8 p-0">
                                        <div class="row mt-2">
                                            {{ form.title.label_tag }}
                                            {{ form.title }}
                                        </div>
                                        <div class="row">
                                            {{ form.desc.label_tag }}
                                            {{ form.desc }}
                                        </div>
                                    </div>
                                    <div class="row d-flex justify-content-center align-items-center my-2">
                                        <div class="col-sm-5">
                                            {{ form.lat.as_field_group }}
                                        </div>
                                        <div class="col-sm-5">
                                            {{ form.lon.as_field_group }}
                                        </div>
                                    </div>
                                    <div class="row d-flex justify-content-center align-items-center">
                                        <button type="submit" class="btn btn-success m-2">Submit</button>
                                    </div>
                                </div>
                                <!-- {{ form.desc.as_field_group }} -->
                            <!-- </div> -->
                            <!-- <div class="row align-items-center justify-content-center"> -->
                                
                            <!-- </div> -->
                            <!-- <div class="col-sm-4 d-flex align-items-center justify-content-center">
                            </div> -->
                        <!-- </div> -->
                        
                    </fieldset>
            
                    <!-- <input type="text" name="lat_field" id="lat_field" hidden="hidden">
                    <input type="text" name="lon_field" id="lon_field" hidden="hidden"> -->
                    <!-- <button type="submit" class="btn btn-danger m-2">Report</button> -->
                </form>
                {% endif %}
                <div class="col-sm-6 col-md-4 d-flex justify-content-center align-items-center">
                    <div style="width: 400; height: 400;">
                        <div id="map" class="w-100 h-100"></div>
                    </div>
                </div>
            <!-- </div> -->
        <!-- </div> -->
    <!-- </div> -->
</div>

{% endblock %}