litter/urls.py
from django.urls import path

from . import views

app_name="litter"
urlpatterns = [
    path("latest/", views.latest, name="latest"),
    path("instance/<int:instance_id>/", views.instance, name="instance"),
    path("report/", views.report, name='report'),
    path("heatmap/", views.heatmap, name='heatmap'),
    path("your-instances/", views.your_instances, name="your instances"),
]

poi/urls.py
from django.urls import path

from . import views

app_name="poi"
urlpatterns = [
    path("map/", views.map, name="map"),
    path("info/<int:poi_id>/", views.information, name="info"),
    path("submit/", views.submit, name='submit'),
]

sustainable_challenges/sustainable_challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sustainable_challenges'

urlpatterns = [
    path('litter/', include('litter.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('authuser.urls')),
    path('game/', include('game.urls')),
    path('account/', include('account.urls')),
    path('study_area/', include('study_area.urls')),
    path('forum/', include('forum.urls')),
    path('poi/', include('poi.urls')),
    path('leaderboard/', include('leaderboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sustainable_challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sustainable_challenges'

urlpatterns = [
    path('litter/', include('litter.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('authuser.urls')),
    path('game/', include('game.urls')),
    path('account/', include('account.urls')),
    path('study_area/', include('study_area.urls')),
    path('forum/', include('forum.urls')),
    path('poi/', include('poi.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litter/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL

class LitterInstance(models.Model):
    '''
    Database model for storing an instance of litter

    Fields
    ------
    user: Django user
          The user who reported this instance of litter
    lat: float
         The latitude of the reports location
    lon: float
         The longitude of the reports location
    img: string
         Path to the image of litter for this instance
    datetime: DateTime
              The Date and Time that this instance was reported
    approved: int
              The status of the report
              0 - pending approval,
              1 - approved,
              2 - rejected,
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")
    lat = models.DecimalField("Latitude", default=0, decimal_places=7, max_digits=10)
    lon = models.DecimalField("Longitude", default=0, decimal_places=7, max_digits=10)
    img = models.ImageField("Image", null=True, blank=True, upload_to='images/litter/')
    datetime = models.DateTimeField("Date submitted")
    approved = models.IntegerField("Approval status", default=0)

    def __str__(self):
        return f"User: {self.user}, {self.lat}, {self.lon} @ {self.datetime}"

litter/forms.py
from django import forms
from .models import LitterInstance

class InstanceForm(forms.ModelForm):
    '''
    The Form for reporting an instance of litter
    The only thing this form will really accept is the image
    Everything else for the LitterInstance model will come from either js or the report view
    '''
    #img = forms.ImageField(label="", widget=forms.ClearableFileInput(attrs={'class': ''}))
    
    class Meta:
        model = LitterInstance
        fields = ('img',)

        widgets = {
            'lat': forms.NumberInput(attrs={'hidden':'hidden'}),
            'lon': forms.NumberInput(attrs={'hidden':'hidden'}),
        }

class ApproveForm(forms.Form):
    '''
    Form for updating the status of an instance
    '''
    choices = ((1, 'Approve'), (2, 'Reject'))
    options = forms.ChoiceField(widget=forms.Select(attrs={'class': 'rounded p-2'}), choices=choices, label='')


class TimeRangeForm(forms.Form):
    '''
    The form for selecting the date time range to display on the heatmap
    '''
    s_date = forms.DateTimeField(label='Start date', widget=forms.DateTimeInput(attrs={'type': 'date', 'class': 'p-1 m-2 rounded'}))
    e_date = forms.DateTimeField(label='End date', widget=forms.DateTimeInput(attrs={'type': 'date', 'class': 'p-1 m-2 rounded'}))

sustainable_challenges/litter/views.py
from typing import Any
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse, HttpResponseForbidden
from .models import LitterInstance
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from .forms import InstanceForm, ApproveForm, TimeRangeForm
from json import dumps
from django.contrib.auth.decorators import login_required
from typing import Union

@login_required
def latest(request: HttpRequest) -> HttpResponse:
    '''
    Endpoint for displaying a list (in date order) of instances that need approving/rejecting

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django

    Returns
    -------
    HttpResponse
        Containing the latest.html webpage
    '''
    if not request.user.is_staff:
        return HttpResponseForbidden()
    
    # Get the pending status instances and order them by oldest first
    valid_instances = LitterInstance.objects.filter(approved=0).order_by("-datetime")
    # Render the webpage
    return render(request, "litter/latest.html", {"latest_instance_list": valid_instances, 
                                                  "is_staff": request.user.is_staff})

@login_required
def your_instances(request: HttpRequest) -> HttpResponse:
    '''
    Endpoint for displaying a list (in date order) of instances reported by the request user

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django

    Returns
    -------
    HttpResponse
        Containing the your-instances.html webpage
    '''
    # Get the instances submitted by this user and order them by oldest first
    instance_list = LitterInstance.objects.filter(user_id=request.user.id).order_by("-datetime")
    # Render the webpage
    return render(request, "litter/your-instances.html", {"instance_list": instance_list, 'is_staff': request.user.is_staff})

@login_required
def instance(request: HttpRequest, instance_id: int) -> Union[HttpResponse, HttpResponseRedirect]:
    '''
    Endpoint for displaying a single instance of litter.
    If a staff user accesses this page, the instance is pending and they're not the one who made the report,
    there will be an option to approve or reject the instance

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django
    instance_id : int
                  The id for the litter instance to view

    Returns
    -------
    HttpResponse or HttpResponseRedirect
        Containing the instance.html webpage.
        If HttpResponseRedirect it means that a POST request was received and accepted
    '''
    submitted = False
    _instance = get_object_or_404(LitterInstance, pk=instance_id)

    if not (request.user.is_staff or request.user.id == _instance.user_id):
        return HttpResponseForbidden()

    if request.method == 'POST':
        if (not request.user.is_staff) or request.user.id == _instance.user_id:
            return HttpResponseForbidden()
        
        form = ApproveForm(request.POST)
        if form.is_valid():
            _instance.approved = form.cleaned_data['options']
            _instance.save()
            if _instance.approved == "1":
                _instance.user.complete_task('litter')
            return HttpResponseRedirect(f'/litter/instance/{_instance.id}?submitted=True')
    else:
        form = ApproveForm
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'litter/instance.html', {'form': form,
                                                   'instance': _instance,
                                                   'submitted': submitted,
                                                   'id': _instance.id,
                                                   "requester_id": request.user.id,
                                                   "is_staff": request.user.is_staff})

@login_required
def report(request: HttpRequest) -> Union[HttpResponse, HttpResponseRedirect]:
    '''
    Endpoint for users to report an instance of litter on campus

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django

    Returns
    -------
    HttpResponse or HttpResponseRedirect
        Containing the report.html webpage.
        If HttpResponseRedirect it means that a POST request was received and some litter was reported
    '''
    submitted = False
    id = -1
    if request.method == "POST":
        # Populate the form with the POST and FILES data
        form = InstanceForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.datetime = timezone.now()  # Add current time
            # lat and lon had to be done in a different part to the model form
            # because the javascript needs to change it
            obj.lat = float(request.POST['lat_field'])
            obj.lon = float(request.POST['lon_field'])
            obj.user_id = request.user.id
            obj.save()
            _instance = LitterInstance.objects.get(datetime=obj.datetime, user_id=obj.user_id)
            return HttpResponseRedirect(f'/litter/report?submitted=True&id={_instance.id}')
    else:  # Is a GET request
        # Create a blank form
        form = InstanceForm
        # Check if the GET request is a result of the redirect after a post
        if 'submitted' in request.GET and 'id' in request.GET:
            submitted = True
            id = request.GET['id']

    return render(request, 'litter/report.html', {'form': form, 
                                                  'submitted': submitted, 
                                                  'id': id,
                                                  'is_staff': request.user.is_staff})

@login_required
def heatmap(request: HttpRequest) -> Union[HttpResponse, HttpResponseRedirect]:
    '''
    Endpoint for staff to view the heatmap of litter on campus.
    There is a form that allows the user to change the datetime range of litter reports that will be
    displayed on the map

    Parameters
    ----------
    request : HttpRequest
              The request object generated by django

    Returns
    -------
    HttpResponse or HttpResponseRedirect
        Containing the heatmap.html webpage.
        If HttpResponseRedirect it means that a POST request was received for changing the datetime range to view
    '''
    if not request.user.is_staff:
        return HttpResponseForbidden()
      
    data = []
    if request.method == 'POST':
        form = TimeRangeForm(request.POST)
        if form.is_valid():
            # Extract the date range
            start_date = form.cleaned_data['s_date'].date()
            end_date = form.cleaned_data['e_date'].date()
            return HttpResponseRedirect(f'/litter/heatmap?start_date={start_date}&end_date={end_date}')
    else:  # Is a GET request
        form = TimeRangeForm
        # If the GET request is a result of the redirect after a post then these GET variables will exist
        if 'start_date' in request.GET and 'end_date' in request.GET:
            # Get instances that are within the specified time range
            approved_instances = LitterInstance.objects.filter(approved=1, datetime__range=[request.GET['start_date'], request.GET['end_date']])
        else:  # If its a GET request without being the result of a redirect
            approved_instances = LitterInstance.objects.filter(approved=1)  # All approved posts
        
        # Convert the data into the form accepted for the heatmap
        for _instance in approved_instances:
            data.append([float(_instance.lat), float(_instance.lon), 1])
        
    # JSON encode it
    dataJSON = dumps(data)

    return render(request, 'litter/heatmap.html', {'data': dataJSON,
                                                    'form': form,
                                                'is_staff': request.user.is_staff})

sustainable_challenges/litter/templates/litter/heatmap.html
{% extends "base.html" %}
{% block content %}
{% if is_staff %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
    integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
<script src="..\..\static\Leaflet.heat-gh-pages\dist\leaflet-heat.js" type="text/javascript"></script>
<style>
    #map {
        position: absolute;
        top: 200;
        bottom: 50;
        left: 100;
        right: 100;
    }
</style>

<div class="row">
    <div class="col-sm-12 align-items-center">
        <form class="d-flex justify-content-center align-items-center h-100" action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success mb-3 mx-2">Submit</button>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div id="map" class=""></div>
    </div>
</div>



<script>
    var map = L.map('map').setView([50.735214, -3.531754], 15);
    L.tileLayer('https://api.maptiler.com/maps/openstreetmap/{z}/{x}/{y}@2x.jpg?key=5CproNoEKyotlpqU4SO8', {
        attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
        tileSize: 512,
        zoomOffset: -1,
    }).addTo(map);
    //L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    //    attribution: 'Maps <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
    //    tileSize: 512,
    //    zoomOffset: -1,
    //pixelRatio: 1,}).addTo(map);

    var data = JSON.parse("{{data}}");
    var heat = L.heatLayer(data, { radius: 25, minOpacity: 0.4, gradient: { 0.3: 'blue', 0.5: 'lime', 0.9: 'red' } }).addTo(map);
</script>
{% else %}
<p>You do not have permission to view this</p>
{% endif %}
{% endblock %}

sustainable_challenges/litter/templates/litter/report.html
{%  extends "base.html" %}
{% block content %}
{% load static %}
    <script src="{% static 'report.js' %}"></script>
    <div class="row">
        <div class="col-sm-12 d-flex justify-content-center align-items-center">
            <h1>Report an instance of litter</h1>
        </div>
    </div>
<br/><br/>
{% if submitted %}
    <div class="row mb-3">
        <div class="col-sm-12 text-center">
            <span class="">Litter reported succefully.</span>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-sm-4 d-flex justify-content-center">
            <a role="button" class="btn btn-success" href="{% url 'litter:instance' id %}">View report</a>
        </div>
    </div>
{% else %}
    <div class="row d-flex justify-content-center">
        <div class="col-sm-12 col-md-8">
            <div class="container-fluid">
                <div class="row d-flex justify-content-center">
                    <form id="form" class="col-sm-12 col-md-8 d-flex justify-content-center align-items-center bg-white rounded" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="d-flex align-items-center mt-3">
                            {{ form.as_p }}
                        </fieldset>
                
                        <input type="text" name="lat_field" id="lat_field" hidden="hidden">
                        <input type="text" name="lon_field" id="lon_field" hidden="hidden">
                        <button type="submit" class="btn btn-danger m-2">Report</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}